//
// Created by Sam on 3/30/2018.
//

#ifndef WHISPERERENGINE_CREATUREDESTROYEDEVENT_H
#define WHISPERERENGINE_CREATUREDESTROYEDEVENT_H


class CreatureDestroyedEvent
{

};


#endif //WHISPERERENGINE_CREATUREDESTROYEDEVENT_H
